name: Deploy Dashboard to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Upload Dashboard
        uses: actions/upload-pages-artifact@v4
        with:
          path: '.github/templates'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
